reflex_mapping_rules:
  STD: "STOCK"
  CAT: "NDISP"
  QUA: "NDISP"
  REC: "NDISP"
  RET: "NDISP"
  BLO: "REJET"
  DEF: "DEF"
  DES: "DES"

m3_mapping_rules:
  - whlo_in: ["100", "150", "400"]
    whsl_eq: "STOCK"
    category: "STOCK"
  - whlo_in: ["100", "400"]
    whsl_eq: "NDISP"
    category: "NDISP"
  - whlo_in: ["100", "400"]
    whsl_eq: "REJET"
    category: "REJET"
  - whlo_in: ["200"]
    whsl_eq: "DEF"
    category: "DEF"
  - whlo_in: ["200"]
    whsl_eq: "DES"
    category: "DES"

m3_depots_columns: ["100", "200", "150", "400"]
